// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdRLZNW0LEBQO2VC9LkHh3qEMKzcdYmY',
    appId: '1:511933512074:web:66c88dc6a9b6b956a03073',
    messagingSenderId: '511933512074',
    projectId: 'mymoim-beb90',
    authDomain: 'mymoim-beb90.firebaseapp.com',
    databaseURL: 'https://mymoim-beb90-default-rtdb.firebaseio.com',
    storageBucket: 'mymoim-beb90.appspot.com',
    measurementId: 'G-4HMF9D79VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdrG-lVUoPlktSnJ52xxdRb4Rnc526cVs',
    appId: '1:511933512074:android:b071b96b861ed026a03073',
    messagingSenderId: '511933512074',
    projectId: 'mymoim-beb90',
    databaseURL: 'https://mymoim-beb90-default-rtdb.firebaseio.com',
    storageBucket: 'mymoim-beb90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQrR2E_IE4sIgwijj9VndFEZC8FNtoSY',
    appId: '1:511933512074:ios:6f032a62854840a1a03073',
    messagingSenderId: '511933512074',
    projectId: 'mymoim-beb90',
    databaseURL: 'https://mymoim-beb90-default-rtdb.firebaseio.com',
    storageBucket: 'mymoim-beb90.appspot.com',
    androidClientId: '511933512074-kg787vclta40qmp8sa8adakvtkbb5kf5.apps.googleusercontent.com',
    iosClientId: '511933512074-9t4vh3ec4hqspeqb2cf4jjsd6stuclmd.apps.googleusercontent.com',
    iosBundleId: 'com.lgsdiamant.mymoim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQrR2E_IE4sIgwijj9VndFEZC8FNtoSY',
    appId: '1:511933512074:ios:6f032a62854840a1a03073',
    messagingSenderId: '511933512074',
    projectId: 'mymoim-beb90',
    databaseURL: 'https://mymoim-beb90-default-rtdb.firebaseio.com',
    storageBucket: 'mymoim-beb90.appspot.com',
    androidClientId: '511933512074-kg787vclta40qmp8sa8adakvtkbb5kf5.apps.googleusercontent.com',
    iosClientId: '511933512074-9t4vh3ec4hqspeqb2cf4jjsd6stuclmd.apps.googleusercontent.com',
    iosBundleId: 'com.lgsdiamant.mymoim',
  );
}
